tao/shell-script/lib/common.sh
Added ${region} parameter to get user arn function
=> Added ${region} parameter to get user arn function

tao/whats_new.md
Added what's new file with TAO dashboard changes
=> Added what's new file with TAO dashboard changes

tao/Readme.md
=> Added note about JSON format for report

cudos/CHANGELOG.md
=> Changelog.md added to CUDOS

cudos/CHANGELOG.md
=> Dashboard version update v4.50

tao/Readme.md
https://github.com/aws-samples/aws-cudos-framework-deployment/issues/8
=> Amended command for refresh dashboard data step

cudos/shell-script/lib/common.sh
=> Update common.sh to properly handle qs identity region

cudos/dashboards/create-cid-dashboard.json, cudos/shell-script/customer-cudos.sh, cudos/shell-script/lib/common.sh
=> cid incuding

cudos/README.md, cudos/shell-script/customer-cudos.sh
=> cid to a separate parameter

README.md
Fixes broken link to CUDOS workshop trends page
=> Fixes broken link to CUDOS workshop trends page

trends/shell-script/trends.sh
*Issue #, if available:* 39
Fix the hardcoded table name "cost_usage" in trends.sh
=> Update trends.sh to fix the hardcoded table name "cost_usage"

cudos/CHANGELOG.md
=> Cetection > Detection

cudos/shell-script/customer-cudos.sh
=> handle the new async behaviour or QS API

tao/shell-script/lib/common.sh
added QS identity region check
=> added QS identity region check

tao/shell-script/lib/common.sh, tao/shell-script/tao.sh
1. Added change-source-location action to change path to s3 bucket with Trusted Advisor reports. Required to simplify switch from TA Org View to Data Collection lab
2. Minor fixes
=> minor fixes and added support of change-source-location

tao/minimal_permissions.json
n/a
- need quicksight:CreateIngestion to refresh data
- need quicksight:PassDataSource and quicksight:PassDataSet to deploy
=> Tao needs quicksight:CreateIngestion, etc to deploy and refresh data

README.md
Updated links from workshops to WA labs, and added a bit more explanation on the first step
=> Updated read me for clarity

cudos/view-templates/compute_savings_plan_eligible_spend.sql, cudos/view-templates/compute_savings_plan_eligible_spend_ri.sql, cudos/view-templates/compute_savings_plan_eligible_spend_sp.sql, cudos/view-templates/compute_savings_plan_eligible_spend_sp_ri.sql, cudos/view-templates/ec2_running_cost.sql, cudos/view-templates/ec2_running_cost_ri.sql, cudos/view-templates/ec2_running_cost_sp.sql, cudos/view-templates/ec2_running_cost_sp_ri.sql, cudos/view-templates/ri_sp_mapping.sql, cudos/view-templates/ri_sp_mapping_ri.sql, cudos/view-templates/ri_sp_mapping_sp.sql, cudos/view-templates/ri_sp_mapping_sp_ri.sql, cudos/view-templates/s3.sql, cudos/view-templates/s3_ri.sql, cudos/view-templates/s3_sp.sql, cudos/view-templates/s3_sp_ri.sql, cudos/view-templates/summary_view.sql, cudos/view-templates/summary_view_ri.sql, cudos/view-templates/summary_view_sp.sql, cudos/view-templates/summary_view_sp_ri.sql, cudos/view-templates/views.json
=> quick fix for view templatex and cfn

cid/common.py
Add CloudShell detection in open()
=> Detect CloudShell in open()

.github/workflows/python-publish.yml, setup.cfg
=> PyPI release automation

setup.cfg
=> Fix cli name

cid/helpers/cur.py, setup.cfg
*Issue #120 , if available:*
Change CUR detection logic
=> Improve CUR detection

cfn-templates/cudos-cfn.yml, cid/builtin/core/data/resources.yaml, setup.cfg
=> Relocate cid template

.gitignore, cid/builtin/core/__init__.py, cid/builtin/core/data/queries/shared/account_map.sql, cid/builtin/core/data/queries/shared/aws_accounts.sql, cid/cli.py, cid/common.py, cid/helpers/account_map.py, cid/helpers/athena.py, cid/helpers/quicksight.py, cid/plugin.py, cid/utils.py, setup.cfg
=> Refactor code, implement logging

cid/cli.py, cid/common.py, cid/helpers/quicksight.py, setup.cfg
=> Fixes to 0.1.6

changes/CHANGELOG-cid.md, changes/CHANGELOG-kpi.md
Added changelogs for KPI and CID 
=> Added changelogs for KPI and CID 

cid/helpers/quicksight.py
=> WIP: Bugfixes/Features

cid/common.py
=> Bugfix: datasets detection

cid/builtin/core/data/queries/kpi/kpi_instance_all_view.sql, cid/builtin/core/data/queries/kpi/kpi_instance_all_view_noRI.sql, cid/builtin/core/data/queries/kpi/kpi_instance_all_view_noRISP.sql, cid/builtin/core/data/queries/kpi/kpi_instance_all_view_noSP.sql
KPI logic spelling error. No changes to field names, etc. 
=> KPI Spelling error

cfn-templates/views_kpi.json
=> Config for kpi dashboard cfn

changes/CHANGELOG-kpi.md
v1.1 with correction for normalized usage calculated field in KPI dashboard
=>  Updated CHANGELOG KPI - v1.1

cid/common.py, cid/helpers/quicksight.py
=> Bugfix: exceptions handling

cid/helpers/quicksight.py
=> Hotfix: failed deployment handling

cid/common.py, cid/helpers/account_map.py, cid/helpers/athena.py, cid/helpers/cur.py, cid/helpers/quicksight.py, cid/utils.py
=> Enhancements: exception logging and refactoring

cfn-templates/kpi.cfn.yml
Introducing the Cloudformation template for the KPI Dashboard
=> Adding Cloudformation Template file for KPI Dashboard

changes/CHANGELOG-kpi.md, cid/builtin/core/data/queries/kpi/kpi_s3_storage_view.sql
=> KPI 1.2 updates

README.md
Demo dashboard urls are broken in readme. This proposes a fix
=> Fix dashboard urls in readme

cfn-templates/cudos-cfn.yml, cfn-templates/kpi.cfn.yml, cfn-templates/tao.cfn.yml
Add logger to TAO and KPI + refactoring
=> Add logger to TAO and KPI CFN + Refactoring of Logging in Cudos CFN

cid/common.py
Adds tracing to the python deploy
=> Add tracking

cid/builtin/core/data/datasets/kpi/kpi_s3_storage_all.json
=> Update KPI dataset update

.gitignore, cid/cli.py, cid/common.py, cid/helpers/quicksight.py, cid/utils.py
=> Feature: sharing

cid/helpers/quicksight.py
Add waiting of dataset creation
=> add waiting for dataset creation

cid/helpers/quicksight.py
=> Feature: detect QuickSight identity region

cid/common.py, cid/helpers/__init__.py, cid/helpers/quicksight/__init__.py, cid/helpers/quicksight/dashboard.py, cid/helpers/quicksight/dataset.py, cid/helpers/quicksight/resource.py
=> Refactor: QuickSight helper

cid/builtin/core/data/queries/co/auto_scale_options.sql, cid/builtin/core/data/queries/co/ebs_volume_options.sql, cid/builtin/core/data/queries/co/ec2_instance_options.sql, cid/builtin/core/data/queries/co/lambda_options.sql
This changes the format of date for COD.
=> fix dates in compute opt dashboard

changes/CHANGELOG-cod.md, cid/builtin/core/data/resources.yaml
Add readme and cleanup definition for COD
=> Add cod readme

cid/builtin/core/data/queries/shared/business_units_map.sql, cid/cli.py, cid/common.py, cid/helpers/athena.py, cid/helpers/glue.py, cid/helpers/quicksight/__init__.py, cid/plugin.py, cid/test/deploy-delete-cid.sh, cid/test/deploy-delete-cod.sh, cid/test/deploy-delete-cudos.sh, cid/utils.py
4-th attempt to set delete views
=> Delete views 4

cid/common.py
=> add confirmation on delete

README.md
=> add url to cod demo

cid/helpers/quicksight/__init__.py
=> fix progress bar

cid/builtin/core/data/queries/cid/ec2_running_cost_ri.sql, cid/builtin/core/data/queries/cid/summary_view.sql, cid/builtin/core/data/queries/cid/summary_view_ri.sql, cid/builtin/core/data/queries/cid/summary_view_sp.sql, cid/builtin/core/data/queries/cid/summary_view_sp_ri.sql
=> summary_view update

cid/common.py, cid/helpers/quicksight/__init__.py, cid/helpers/quicksight/dashboard.py, cid/helpers/quicksight/datasource.py, cid/utils.py
=> Bugfix: resource management

cid/common.py
=> Improve logging

cid/helpers/quicksight/__init__.py
=> Bugfix: older Python compatibility

cid/builtin/core/data/resources.yaml, cid/test/deploy-delete-cod.sh
Fix lambda path for COD deployment
=> Fix default lambda path for COD

cid/common.py
=> Bugfix: custom dahboard Id

cid/helpers/quicksight/__init__.py
=> add better error message for Ent Ed of Quicksight

README.md
=> add table in readme

cid/helpers/quicksight/__init__.py
Fix for cases when we do not have permission to read user in quicksight.
=> fix QuickSight user choice

cid/common.py, cid/helpers/athena.py, cid/helpers/glue.py
Add some logs and fix some typos
=> Minoir fixes and better logs

cid/builtin/core/data/permissions/dashboard_permissions.json, cid/builtin/core/data/permissions/data_set_permissions.json, cid/builtin/core/data/permissions/data_source_permissions.json, cid/builtin/core/data/permissions/folder_permissions.json, cid/common.py, cid/helpers/quicksight/__init__.py
=> Refactor resource permissions 

cfn-templates/tao.cfn.yml
Fix hard coded glue table name in tao dataset in CFN
=> tao: remove hardcoded glue table name in dataset

cid/helpers/athena.py
fix #292: manage default data catalog if multiple exist
=> fix #292: manage default data catalog if multiple exist

cid/helpers/account_map.py, cid/helpers/athena.py
This limits the number of attempts to create map to 3 and add a log if sql fails
=> Add logs and limit map attempts

cid/cli.py, cid/common.py
=> allow choosing datasource arn

cid/common.py
=> avoid fail on an empty account

.github/workflows/codeguru-reviewer.yml, .github/workflows/codeql-analysis.yml
=> Code Analysis

changes/CHANGELOG-cid.md
=> Updated change log with CID v3.1

cid/common.py
=> Fix syntax error

cid/builtin/core/data/permissions/dashboard_link_permissions.json, cid/cli.py, cid/common.py, requirements.txt, setup.cfg
=> Feature: Share with an account

cid/cli.py, cid/common.py
add deployment from resources file (only Datasets and Dashboards are supported)
=> add deployment from resources file

cid/cli.py, cid/common.py, cid/export.py, cid/helpers/quicksight/__init__.py
=> add export functionality

cid/helpers/athena.py
=> avoid fail of table discover on a big number of tables in database

cid/common.py
=> fix error with share-with-account

cid/utils.py
*Description of changes:*:
Avoid potential issues with formatting of complex objects, other than strings. 
=> fix: formatting must not be applied to values others than string

changes/CHANGELOG-cudos.md
=> CUDOS v4.72

assets/recommended_permissions.json, cid/common.py, cid/helpers/quicksight/__init__.py
*Issue #332, if available:*
Enables checking QuickSight subscription before moving to the `deploy` flow.
=> Check QuickSight subscription

cid/helpers/athena.py
=> Check if WorkGroup is usable

cid/base.py, cid/builtin/core/data/permissions/dashboard_link_permissions.json, cid/cli.py, cid/common.py, cid/helpers/account_map.py, cid/helpers/athena.py, cid/helpers/cur.py, cid/helpers/glue.py, cid/helpers/quicksight/__init__.py, cid/utils.py
New Class CidBase to simplify session management in other classes.
=> Enhancement: CidBase class

cid/helpers/account_map.py
=> avoid finally as it is executed even if the error is thrown

cid/cli.py
Add `--profile` parameter option to unify with aws cli
=> Parameter: profile

cid/common.py, cid/export.py, cid/helpers/quicksight/__init__.py
=> Enhancement: templates in any region

cid/base.py, cid/builtin/core/data/datasets/cid/compute.json, cid/builtin/core/data/datasets/cid/ec2_running_cost.json, cid/builtin/core/data/datasets/cid/s3_view.json, cid/builtin/core/data/datasets/cid/summary_view.json, cid/builtin/core/data/datasets/co/dataset.json, cid/builtin/core/data/datasets/kpi/kpi_ebs_snap.json, cid/builtin/core/data/datasets/kpi/kpi_ebs_storage_all.json, cid/builtin/core/data/datasets/kpi/kpi_instance_all.json, cid/builtin/core/data/datasets/kpi/kpi_s3_storage_all.json, cid/builtin/core/data/datasets/kpi/kpi_tracker.json, cid/builtin/core/data/datasets/shared/customer_all.json, cid/builtin/core/data/datasets/tao/dataset.json, cid/builtin/core/data/datasets/trends/daily_anomaly_detection.json, cid/builtin/core/data/datasets/trends/monthly_anomaly_detection.json, cid/builtin/core/data/datasets/trends/monthly_bill_by_account.json, cid/builtin/core/data/permissions/dashboard_permissions.json, cid/builtin/core/data/permissions/dashboard_permissions_namespace.json, cid/builtin/core/data/permissions/data_set_permissions.json, cid/builtin/core/data/permissions/data_source_permissions.json, cid/builtin/core/data/permissions/folder_permissions.json, cid/common.py, cid/helpers/quicksight/__init__.py, cid/logger.py, cid/plugin.py
=> Refactor permission management

cid/helpers/account_map.py
=> cover cur_table_name with quotes to support names with '-'

cid/helpers/quicksight/__init__.py
=> Catch SPICE quota exception

.github/workflows/python-publish.yml, .github/workflows/tests.yml, assets/publish_lambda_layer.sh
=> Stage Lambda Layers

cid/builtin/core/data/queries/kpi/kpi_instance_all_view.sql
=> exclude windows from ec2_graviton_eligible_cost

cfn-templates/cid-cfn.yml
=> fix tables for multi acc

.github/workflows/python-publish.yml
=> Add release LambdaLayer

cid/common.py
This fixes an undef variable issue that for some reason skipped our tests up until now
=> fix undefined var issue

cfn-templates/cid-cfn.yml
- Align CUR variables in CFN. 
- Rename CurIsAggregated to CURIsManagedWithCloudFormation
- add a variable {account_id}
=> rename CurIsAggregated to CURIsManagedWithCloudFormation

cid/common.py
Correctly manage quicksight-datasource-id
=> fix-datasource-management

.github/workflows/tests.yml, assets/minimal_permissions.json, cfn-templates/cid-cfn.tests.bats, cid/cli.py, cid/common.py, cid/helpers/athena.py, cid/helpers/quicksight/__init__.py, cid/helpers/quicksight/dataset.py, cid/test/bats/10-deploy-update-delete/cudos.bats, cid/utils.py
=> Fix ci tests

cid/builtin/core/data/queries/cid/ri_sp_mapping_ri.sql, cid/builtin/core/data/queries/cid/ri_sp_mapping_sp.sql, cid/builtin/core/data/queries/cid/ri_sp_mapping_sp_ri.sql
=> Athena v3 compatibility fix

.github/workflows/python-publish.yml, assets/publish_lambda_layer.sh
=> Reduce noise in release GH action

README.md
=> Minor Readme fix (Manual is deprecated)

cfn-templates/cid-cfn.yml
=> remove GlueService role - not needed any more

cid/base.py, cid/common.py, cid/helpers/__init__.py, cid/helpers/quicksight/__init__.py, cid/helpers/quicksight/dashboard.py, cid/helpers/quicksight/dataset.py, cid/helpers/quicksight/template.py, requirements.txt, setup.cfg
=> Feature: check datasets contain all template fields

changes/CHANGELOG-cudos.md
=> CUDOS v4.75

cfn-templates/cid-cfn.yml
- Remove CURIsManagedByCloudFormation parameter (autodetect partitions from the CUR path)
- Refactor parameters order and messages
=> Fix cfn parameters and validation

cfn-templates/cid-cfn.yml
=> minor fix: format message in cfn

cid/helpers/quicksight/__init__.py, cid/helpers/quicksight/dashboard.py
=> fix for cases when template is not detected

cid/helpers/quicksight/__init__.py
Also add a better comment for SPICE capacity exception
=> Bugfix: in case if exising dataset or folder the exception was raised fixing that.

cid/helpers/quicksight/__init__.py
=> Bugfix: Discover deployed template before checks

cfn-templates/cid-cfn.yml
=> add explicit catalog option

cfn-templates/cid-cfn.yml, cid/builtin/core/data/resources.yaml
=> align s3 path with the latest updates in DataCollectionLab

cid/cli.py, cid/common.py, cid/helpers/quicksight/__init__.py
…but still fail if template is not found for deployment
=> bugfix: Not fail if template is not found for a deployed dashboard 

assets/publish_lambda_layer.sh
=> better release script - add publish of cfn and cleanup

cid/helpers/athena.py
=> better error messages for missing athena q location

cid/utils.py
=> release/0.2.8 - fix user input capabilites for bitbash on windows

cid/common.py, cid/export.py, cid/helpers/quicksight/__init__.py, cid/helpers/quicksight/dashboard.py, cid/helpers/quicksight/template.py
Automatic detection of CID major version bump and ask user for recursive update. 
- Various bug fixes 
- Addition of cid_version on template class from Description parameters 
- Additional information about cid_version in status command 
=> Add recursive on version bump

cid/common.py
=> Changed customer question for major version update

cfn-templates/cid-cfn.tests.bats, cfn-templates/cid-cfn.yml
This fixes CFN permissions, making them more strict. Also fixes some test issues as well  
- make the kms permissions optional and configurable
- where possible use WorkGroup and Database permissions
- limit permissions on user ListUsers and DescribeUser
=> Fix cfn permissions

cfn-templates/cid-cfn.yml
=> refactor refresh lambda - add paginator

cid/utils.py
=> add cid_print

requirements.txt, setup.cfg
=> release/0.2.8 - update version of boto3 for the latest qs api

cid/cli.py, cid/common.py
Add an option to load resources from https 
=> add https resources

cid/helpers/quicksight/__init__.py
=> release/0.2.8 - fix group management

README.md
updated cid-cmd delete command description and usage
=> update cid-cmd delete command usage

cid/common.py
=> fix empty deployedtemplate

cid/helpers/quicksight/__init__.py
=> bugifx : invalidate cache on dataset update

cid/common.py
=> refactor dataset management

cid/builtin/core/data/resources.yaml, cid/helpers/quicksight/__init__.py
=> ADD version definition override from definition file

cid/cli.py, cid/export.py
=> minor changes in export

cid/builtin/core/data/queries/tao/ta_org_view.sql
=> timestamp should be in unix time

cid/common.py
=> check if deployedTemplate retrieved before getting version

cid/common.py, cid/helpers/athena.py
=> bugfix: avoid workgroup scan

cid/common.py
Raising proper error when checking CUR enablement
=> Raising proper error when checking CUR enablement

cid/export.py
=> Raise an error in unsupported joins in export

cid/builtin/core/data/queries/cid/summary_view.sql, cid/builtin/core/data/queries/cid/summary_view_ri.sql, cid/builtin/core/data/queries/cid/summary_view_sp.sql
=> aligning summary_view with approx_distinct

cid/cli.py, cid/utils.py
add check for available update of cid-cmd on pypi
=> feature: add check for update of cid-cmd on pypi

cid/builtin/core/data/queries/shared/account_map.sql
=> Avoid empty account names

cfn-templates/cid-cfn.yml, cid/common.py, cid/helpers/quicksight/__init__.py
=> datasource management in paris

cid/helpers/csv2view.py
=> add sniffer for csv

cfn-templates/cid-cfn.yml, cid/common.py
=> limit error message in cfn and rework dataset management (process multiple datasets)

cid/helpers/quicksight/__init__.py
=> refactoring of dashobard info fetching

cid/helpers/quicksight/__init__.py
Handle the legacy dashboard template source arn without version. 
* Check if the template contain a version and do not crash 
* Use default version found in resources.yml file when there is no version
=> bugfix: handle legacy template arn without version

cid/common.py
=> fix required_datasets_names

cid/helpers/quicksight/__init__.py
* refactoring of dashobard info fetching ---------
=> refactoring of dashobard info fetching (#493)

.github/workflows/security-scan.yml, pyproject.toml
=> add security scanner configuration

.bandit, .github/workflows/security-scan.yml, cid/common.py, pyproject.toml
=> Fix scurity scan - move bandit conf to a deparate file

cid/helpers/cur.py
=> add Lake Formation warning

cfn-templates/cid-cfn.yml
=> fix description for OptimizationDataCollectionBucketPath

cid/common.py
* Variable `ds` is used before it is declared
=> used undeclared variable

cid/builtin/core/data/queries/shared/account_map.sql
* Added missing closing bracket
=> missing closing bracket

cid/builtin/core/data/datasets/shared/customer_all.json
=> remove all tags from customer_all

cfn-templates/cur-aggregation.yaml
=> Move cur aggregation

cid/common.py, cid/helpers/quicksight/__init__.py
Added function which creates refresh schedules for new created dataset
=> added function which creates refresh schedules for new created dataset

cid/common.py
=> bugfix: allow dateset creation

cid/helpers/athena.py
=> better error message

terraform-modules/README.md, terraform-modules/cur-setup-source/README.md
*Description of changes:* Add global README for Terraform module documentation
=> Improve documentation for TF modules

cid/helpers/cur.py
=> support athena view as CUR source table

.github/workflows/codeguru-reviewer.yml, .github/workflows/python-publish.yml, .github/workflows/tests.yml
=> fix ci - switch to a newer version of configure-aws-credentials

cid/common.py
=> fix - give a priority to exported resources over core ones

cid/builtin/core/data/queries/co/auto_scale_options.sql
=> fix autoscale dashboard

changes/CHANGELOG-cod.md, cid/builtin/core/data/queries/co/ebs_volume_options.sql
=> fix regression on ebs option filter

cid/helpers/cur.py
=> better message for cur not found error

cid/builtin/core/data/queries/shared/aws_regions.sql, cid/helpers/timezone.py
=> Add il region

cfn-templates/cid-admin-policies.yaml
=> move cid-admin to managed policies and fix bugs

cfn-templates/cid-cfn.yml
=> fix schedules

cfn-templates/tests/test_deploy_with_permissions.py
=> Add cfn test

cid/helpers/quicksight/__init__.py, cid/utils.py
=> fix ThrottlingException

cid/common.py
=> add parameters via athena

.github/workflows/security-scan.yml, cid/common.py
=> Fix cleanup

cid/cli.py, cid/common.py, cid/helpers/quicksight/__init__.py
=> better role handling on datasource creation and minor fixes

cid/common.py
=> fix logic of update in a conner case

cid/base.py, cid/helpers/__init__.py, cid/helpers/athena.py, cid/helpers/s3.py
=> Added automated Athena workgroup creation if missing

cid/helpers/quicksight/__init__.py
=> typo and lint

assets/publish_lambda_layer.sh
=> fix release script

cid/helpers/athena.py, cid/helpers/quicksight/__init__.py, cid/helpers/s3.py
=> Bugfix for workgroup creation in non us-east-1 region

cfn-templates/cid-cfn.yml
=> Adding missing perms, this prevents applying rls on customer_all ds

cid/common.py
=> Expanding load resources

cfn-templates/cid-cfn.yml
=> Fix cfn - add databases permissions for data collection lab

cfn-templates/cid-cfn.yml
=> allow data collection bucket not to exist

cfn-templates/cid-admin-policies.yaml, cfn-templates/cid-cfn.yml
=> Fix permisions

cfn-templates/cur-aggregation.yaml
=> fix some titles in cur deploy

bump-release.py, cfn-templates/cid-cfn.yml
=> chnage names of resources for better update and remove CidVersion

cid/builtin/core/data/queries/cudos/hourly_view_sp_ri.sql
=> fix hourly_view

cid/common.py, cid/test/python/test_merge.py, cid/utils.py, requirements.txt, setup.cfg
=> replace deepmerge by custom code

cid/common.py
=> fix-empty-categories

cid/test/bats/10-deploy-update-delete/cudos.bats
=> change test to cudos v5

README.md
=> update demo links

dashboards/aws-marketplace/aws-marketplace-spg.yaml, dashboards/catalog.yaml
This change allows users to configure AWS Marketplace Single Pane of Glass (SPG) Dashboard v1 to view visualizations for AWS Marketplace spend. 
=> AWS Marketplace Single Pane of Glass (SPG) Dashboard v0.0.1

requirements.txt, setup.cfg
=> update boto3 requirements

cid/helpers/cur.py, cid/helpers/quicksight/__init__.py
=> Better error handling

assets/lint.sh
=> add checkov lints script

cid/helpers/quicksight/__init__.py
=> fix definitions deploy

cid/cli.py, cid/common.py
=> allow choice of category

cid/helpers/csv2view.py
=> ignore non utf8 characters in csv. Otherwise non utf8 breaks csv2view 

cfn-templates/cid-cfn.yml
=> Update links and bucket name to reflect data collection v3

cfn-templates/cid-cfn.tests.bats, cid/builtin/core/data/resources.yaml, cid/test/bats/10-deploy-update-delete/compute-optimizer-dashboard.bats, cid/test/bats/10-deploy-update-delete/ta-organizational-view.bats
=> adjusting default s3 path to cid-data- prefix

cfn-templates/cid-cfn.yml
=> fix update from legacy

cid/common.py
=> support paritions

cid/common.py
=> more resilence to catalog errors

cid/base.py, cid/common.py
=> make url compatibile with China regions

cid/helpers/quicksight/__init__.py
=> create schedule even if we cannot see it

cfn-templates/cid-cfn.yml
=> Fixes for KMS bucket encryption use case

cfn-templates/cid-cfn.yml
=> Fix stack deletion

cid/common.py
=> removing default choice

dashboards/catalog.yaml, dashboards/rds-extended-support-cost-projection/rds-extended-support-cost-projection.yaml
Adding RDS Extended Support cost projection dashboard definition and catalog entry.
=> Adding RDS Extended Support Cost Projection

.github/workflows/security-scan.yml, .github/workflows/tests.yml, cid/common.py, setup.cfg
=> remove support of python3.7 and 3.8, add 3.12 and Bump boto3 

dashboards/catalog.yaml, dashboards/extended-support-cost-projection/extended-support-cost-projection.yaml
=> rename rds extended support to extended support

dashboards/graviton-opportunities-dashboard/graviton_dashboard.yaml
=> Update dashboard id in graviton_dashboard.yaml

dashboards/graviton-opportunities-dashboard/graviton_dashboard.yaml
=> Update graviton_dashboard.yaml, remove parent_account_id

cfn-templates/cid-cfn.yml
=> fix-policies-duplication

cid/builtin/core/data/resources.yaml, cid/test/bats/10-deploy-update-delete/compute-optimizer-dashboard.bats
=> fix co path

dashboards/catalog.yaml, dashboards/scad-containers-cost-allocation/scad-containers-cost-allocation.yaml
=> new dashboard scad-cca

dashboards/scad-containers-cost-allocation/scad-containers-cost-allocation.yaml
=> Changed SCAD dashboard category to "Additional"

changes/CHANGELOG-extended-support-cost-projection.md
=> Added change log for the EKS Extended Support Cost Projection dashboard.

cid/helpers/cur.py
=> better col management

dashboards/scad-containers-cost-allocation/scad-containers-cost-allocation.yaml
Removed resource_tags_user_eks_cluster_name
=> Removed resource_tags_user_eks_cluster_name

changes/CHANGELOG-scad-cca.md
=> SCAD CCA title fix

dashboards/scad-containers-cost-allocation/scad-containers-cost-allocation.yaml
Added reservation_reservation_a_r_n to CUR
=> Added reservation_reservation_a_r_n to CUR

dashboards/extended-support-cost-projection/extended-support-cost-projection.yaml
Adding Aurora MySQL 2.11.5 to the release calendar table
=> Extended Support cost proj. release calendar update

dashboards/extended-support-cost-projection/extended-support-cost-projection.yaml
RDS Extended Support - Adding placeholder to resolve the optimisation data DB inventory table for RDS instances.
=> RDS Ext. Support - Fixing placeholder for optimisation data RDS inventory table

terraform-modules/cur-setup-destination/README.md, terraform-modules/cur-setup-destination/main.tf, terraform-modules/cur-setup-destination/variables.tf, terraform-modules/cur-setup-source/README.md, terraform-modules/cur-setup-source/main.tf, terraform-modules/cur-setup-source/variables.tf
Activate `SPLIT_COST_ALLOCATION_DATA` option
=> fix: activate SPLIT_COST_ALLOCATION_DATA option

cid/helpers/iam.py
=> fix the fallback role

changes/CHANGELOG-graviton-opportunities.md, dashboards/graviton-opportunities-dashboard/graviton_dashboard.yaml
=> yaml template for Graviton Dashboard v1.0.2

cid/common.py, cid/helpers/iam.py, cid/helpers/quicksight/__init__.py
=> china friendly arns

assets/publish_lambda_layer.sh
=> add-upload-feature

cid/cli.py, cid/common.py, cid/helpers/iam.py
=> Manage service roles and allow customer defined buckets to be added to QS role

dashboards/cost-intelligence/cost-intelligence.yaml
=> add cost intelligence

cfn-templates/cid-cfn.yml
=> restrict-cloudwatch-permissions

cid/cli.py, cid/helpers/quicksight/__init__.py
=> allow custom theme

dashboards/health-events/health-events.yaml
=> remove not needed fields

changes/CHANGELOG-hed.md, dashboards/health-events/health-events.yaml
=> health-events 1.0.3

cid/common.py
=> add a wait after cur table creation

cid/common.py
=> add-data-exports

.github/workflows/tests.yml
=> fix-test-pipeline

cfn-templates/data-exports-aggregation.yaml, dashboards/catalog.yaml, dashboards/focus/focus.yaml
=> Add FOCUS data aggregation and dashboard

cfn-templates/cur-aggregation.yaml
=> fix-permissions

cfn-templates/data-exports-aggregation.yaml
=> fix data exports as they need additional permissions in lambda role

cfn-templates/cid-admin-policies.yaml, cfn-templates/cid-cfn.yml, cfn-templates/tests/test_deploy_with_permissions.py
=> remove paris exception and add fixes to test it

cfn-templates/cid-admin-policies.yaml, cfn-templates/cid-cfn.yml, cfn-templates/tests/test_deploy_with_permissions.py
=> Updated permissions and crawler check logic

cfn-templates/data-exports-aggregation.yaml
=> replace - with _ in prefix for Glue table name

cfn-templates/cid-cfn.yml
Users often miss this question as it's in a section labeled as "Please do not change", so moved it to the Common Parameters section at the top, still defaulted the selection to No.
=> Moved LakeFormation question out of Technical Parameters section

cid/helpers/athena.py
=> fix athena database error

assets/publish_lambda_layer.sh
=> extend upload script

cfn-templates/cid-cfn.yml, cfn-templates/data-exports-aggregation.yaml, cfn-templates/tests/test_deploy_with_permissions.py, cid/common.py, cid/helpers/iam.py
=> Add data export permissions

dashboards/aws-feeds/aws-feeds.yaml
Add 3rd party Feed list to AWS News Feed dashboard
=> Add 3rd party Feed list to AWS News Feed dashboard

cfn-templates/cid-cfn.yml, cid/helpers/cur.py
=> Better names for cfn

dashboards/health-events/health-events.yaml
Rework flow and content of the summary tab
Reduce KPI count
Add instructions
Move Event Explorer to the second tab
Rename Resource Detail to Resource Explorer
=> Health events dash 1.0.6

terraform-modules/cur-setup-destination/README.md, terraform-modules/cur-setup-destination/main.tf, terraform-modules/cur-setup-destination/variables.tf, terraform-modules/cur-setup-source/README.md, terraform-modules/cur-setup-source/main.tf, terraform-modules/cur-setup-source/variables.tf
Adds tags to tf managed s3 buckets.
=> terraform-modules: Adds tags input for tf managed s3 buckets

cfn-templates/data-exports-aggregation.yaml
=> add qs policy to data-export

requirements.txt, setup.cfg
=> update boto 1-34-90

cid/common.py, cid/utils.py
=> Stop creating cur table in lambda

dashboards/health-events/health-events.yaml
Improvements to UX of Summary tab, driving consistency across all tabs
=> HED 1.0.8 clarity, consistency, clean up

cfn-templates/data-exports-aggregation.yaml
=> Add coh recommendations to Data Export CFN

dashboards/graviton-opportunities-dashboard/graviton_dashboard.yaml
=> fix graviton dashboard data issue

changes/CHANGELOG-extended-support-cost-projection.md, dashboards/extended-support-cost-projection/extended-support-cost-projection.yaml
Adjusting queries and filters for Aurora serverless V1 and V2 resources.
=> Extended Support Cost Projection - Aurora Serverless adjustments

cfn-templates/data-exports-aggregation.yaml
=> fix export coh and comments

cfn-templates/data-exports-aggregation.yaml
=> add creation of service role automatically

dashboards/health-events/health-events.yaml
=> Usability improvements to Health Events Dashboard

dashboards/health-events/health-events.yaml
=> fix-health

dashboards/extended-support-cost-projection/extended-support-cost-projection.yaml
=> fix extended-support-cost-projection

cfn-templates/data-exports-aggregation.yaml
=> Fix discount type

dashboards/aws-feeds/aws-feeds.yaml
=> fix feeds databases

cfn-templates/data-exports-aggregation.yaml
=> Fix ri/sp time colum types

dashboards/sustainability-proxy-metrics/sustainability-proxy-metrics.yaml
=> fix merge issue

cfn-templates/data-exports-aggregation.yaml
=> add line_item_usage_account_name

changes/CHANGELOG-graviton-opportunities.md, dashboards/graviton-opportunities-dashboard/graviton_dashboard.yaml
Fix broken hyperlinks under Additional Resources
Fix broken hyperlinks under Additional Resources
=> Graviton Dashboard 1.1.1

dashboards/sustainability-proxy-metrics/sustainability-proxy-metrics.yaml
=> fix sql error blocking depolyment. End to end test

cfn-templates/cid-cfn.yml
=> make sharing optional

dashboards/health-events/health-events.yaml
Fixed sort of event explorer chart
Tweaked guidance test
Color consistency between tabs
=> Repair sort, guidance tweaks

cid/export.py
=> fix export by QueryExecutionMode - not supported

dashboards/aws-marketplace/aws-marketplace-spg.yaml
=> add-marketplace-v2

dashboards/aws-budgets/aws-budgets.yaml
=> Fix for budgets dashboard

dashboards/cudos/CUDOS-v5.yaml
=> fix for china

cid/common.py
=> better messages and proccess major version update

cid/export.py
=> allow-multi-database-export

changes/CHANGELOG-aws-cost-anomalies.md, dashboards/cost-anomalies/cost-anomalies.yaml
=> cost anomalies dashboard v1.1.0

dashboards/aws-budgets/aws-budgets.yaml
=> Fix for budget filters aws-budgets.yaml

changes/cloud-intelligence-dashboards.rss
Added the new CID RSS Feed XML file.
This is the initial XML for testing. Later on we can make it the official RSS Feed document for keeping the CID community up to date with changes.
=> Creating the initial cloud-intelligence-dashboards RSS Feed XML

cid/cli.py
=> document --share-with-account 

dashboards/cora/cora.yaml
=> fix-cora-databases

cfn-templates/cid-cfn.yml
=> fix co for rds

cid/helpers/cur.py, dashboards/scad-containers-cost-allocation/scad-containers-cost-allocation.yaml
=> fix-fields-for-scad

cfn-templates/cid-cfn.yml
=> more logical legacy cur management

cid/builtin/core/data/queries/co/auto_scale.json, cid/builtin/core/data/queries/co/ebs_volume.json, cid/builtin/core/data/queries/co/ec2_instance.json, cid/builtin/core/data/queries/co/lambda.json, cid/builtin/core/data/queries/co/rds_database.json, cid/builtin/core/data/queries/shared/cur.yaml, cid/builtin/core/data/queries/tao/glue_table.json, cid/common.py, cid/helpers/cur.py, dashboards/scad-containers-cost-allocation/scad-containers-cost-allocation.yaml
=> fix tao var name

dashboards/graviton-savings-dashboard/graviton_savings_dashboard.yaml
=> Fixing URL formatting

dashboards/graviton-savings-dashboard/graviton_savings_dashboard.yaml
Updated field colors and default filter
=> Updated field colors and default filter

dashboards/extended-support-cost-projection/extended-support-cost-projection.yaml
=> convert extended support to cur2

changes/CHANGELOG-graviton-savings.md, dashboards/graviton-savings-dashboard/graviton_savings_dashboard.yaml
CUR2 Support
OpenSearch and Elasticache filters
=> CUR2 Support

dashboards/graviton-savings-dashboard/graviton_savings_dashboard.yaml
https://github.com/aws-samples/aws-cudos-framework-deployment/issues/919
Missing product_location in cur_proxy
=> Missing product_location in cur_proxy

cfn-templates/cid-cfn.yml
=> add lake formation for the role

cid/helpers/quicksight/__init__.py
=> avoid false error messages on incremental config

cfn-templates/data-exports-aggregation.yaml, changes/CHANGELOG-focus.md, dashboards/focus/focus.yaml
=> Switch to FOCUS 1.0 GA table

cfn-templates/cid-cfn.yml
Add permissions to allow deletion of Athena views using CFN plugin
=> Fix CIDExecRole permissions to allow Athena table delete

changes/CHANGELOG-cudos.md
=> CUDOS v5.5

dashboards/cost-anomalies/cost-anomalies.yaml
https://github.com/aws-samples/aws-cudos-framework-deployment/issues/1056
=> Add anomalies schedule

cid/builtin/core/data/datasets/tao/dataset.json
=> fix  account id for TAO

cfn-templates/cid-cfn.yml
=> Add account-map-database env variable

cid/utils.py
=> fix-utils-for-python39

cid/export.py
=> fix export

cfn-templates/cid-admin-policies.yaml
=> Allow updatedatasets

changes/CHANGELOG-amazon-connect.md, dashboards/amazon-connect/amazon-connect.yaml
=> amazon connect v1.0.1 bug fixes 1-7

requirements.txt, setup.cfg
=> push boto update

cid/helpers/cur_proxy.py
=> allow resource_tags to be unicode

cid/builtin/core/data/queries/kpi/kpi_ebs_storage_view.sql, cid/builtin/core/data/queries/kpi/kpi_instance_all_view.sql, cid/builtin/core/data/queries/kpi/kpi_s3_storage_view.sql
https://github.com/aws-samples/aws-cudos-framework-deployment/issues/1088
in CUR2 we can have NULLs and it breaks KPI logic in some cases
=> avoid nulls for cur2 in kpi

dashboards/scad-containers-cost-allocation/scad-containers-cost-allocation.yaml
=> SCAD v2.0.0 updates

changes/CHANGELOG-scad-cca.md
Updates on changes in SCAD CCA v2.0.0
=> SCAD CCA v2.0.0

changes/CHANGELOG-scad-cca.md
Added upgrade note for deleting QuickSight dataset and Athena view
=> Added upgrade note

changes/CHANGELOG-scad-cca.md
Added new lines to SCAD CCA update notes
=> Added new lines to SCAD CCA update notes

changes/CHANGELOG-hed.md, dashboards/health-events/health-events.yaml
Guidance improvements and tweak of query to incorporate older data. Both should help customers better use the data range filter and see more relevant open or upcoming events.
=> Health events dash 2.1.0

dashboards/health-events/health-events.yaml
=> fixes for health

changes/CHANGELOG-cora.md, dashboards/cora/cora.yaml
=> cora v0.0.7

changes/CHANGELOG-hed.md, dashboards/health-events/health-events.yaml
=> Health events dash 2.1.0 - fix to QS export anomaly

cfn-templates/cid-cfn.yml, cfn-templates/cid-lakeformation-prerequisite.yaml
=> add lf support

cid/helpers/cur.py, cid/helpers/glue.py, cid/helpers/iam.py
=> minor logging fixes

changes/CHANGELOG-amazon-connect.md, dashboards/amazon-connect/amazon-connect.yaml
=> updating connect dashboard version to v1.1.0

changes/CHANGELOG-amazon-connect.md, dashboards/amazon-connect/amazon-connect.yaml
=> updating filter settings for DailyUsage>InboundMins

cid/helpers/quicksight/__init__.py
*Issue # https://github.com/aws-samples/aws-cudos-framework-deployment/issues/1142
*Description of changes: Adding Pagination for cid-helper-quicksight-list_groups*
=> Adding Pagination for cid-helper-quicksight-list_groups

assets/publish_lambda_layer.sh
=> fix release for cfn

cfn-templates/cid-plugin.yml
*Issue #, if available:* Deployment of CORA dashboard with CFN fails without this parameter.
Add parameter required to deploy CORA dashboard with CFN. 
=> Add parameter needed for CORA dashboard

cfn-templates/cid-cfn.yml
=> bucketsync issue fixed

cfn-templates/cid-cfn.yml
=> s3 arn changed from * and condition to arn with AWS::Partition

cid/common.py
=> fix cleanup dataset deletion

cfn-templates/cid-cfn.yml
=> Update CidExec Lamda parameters

dashboards/kpi_dashboard/kpi_dashboard.yaml
=> add kpi dash

cfn-templates/cid-cfn.yml
=> fix for default locations for compute optimizer

README.md, assets/images/deployment-guide-button.svg, assets/images/documentation.svg
=> add button

changes/CHAMGELOG-sustainability-proxy-metrics.md
=> added sustainability proxy metrics dashboard changelog

.github/workflows/publish-rss.yml
=> set content type in s3 metadata

cid/common.py, cid/utils.py
=> fix default choice when fuzzy input

CID-CMD.md
=> fix CID-CMD help

dashboards/aws-budgets/aws-budgets.yaml
https://github.com/aws-solutions-library-samples/cloud-intelligence-dashboards-framework/issues/1202
=> Add check for 0 budget limit

dashboards/cudos/CUDOS-v5-definition.yaml
=> typos in cudos

cid/helpers/quicksight/dataset.py, dashboards/cora/cora.yaml
=> fix athena types detection

cid/export.py
=> fix for custom-sql export

dashboards/cost-intelligence/cost-intelligence-definition.yaml
=> Fix link to the doc on About page

changes/CHANGELOG-cora.md, changes/cloud-intelligence-dashboards.rss, dashboards/cora/cora.yaml
=> CORA v0.0.9

cid/builtin/core/data/queries/co/idle.json, cid/builtin/core/data/queries/co/idle_options.sql
*Issue #1195:*
Fixes StorageDescriptor column name
=> fix StorageDescriptor column name

cfn-templates/cid-cfn.yml
=> limit error message

cid/export.py
=> fix export name

dashboards/data-collection-monitor/data-collection-monitor.yaml
QS export has a defect in the definition of visuals with hidden fields that have no defined column name. This push corrects for that
=> Correct for QS defect on export of hidden

cid/common.py
=> allow parameters dependency

CID-CMD.md, README.md, cfn-templates/cid-cfn.yml, changes/CHANGELOG-cora.md, changes/CHANGELOG-cudos.md, changes/cloud-intelligence-dashboards.rss, dashboards/aws-budgets/aws-budgets.yaml, dashboards/cora/cora.yaml, dashboards/cost-anomalies/cost-anomalies.yaml, dashboards/cost-intelligence/cost-intelligence-definition.yaml, dashboards/cudos/CUDOS-v5-definition.yaml, dashboards/data-collection-monitor/data-collection-monitor.yaml, dashboards/euc/euc-dashboard.yaml, dashboards/extended-support-cost-projection/extended-support-cost-projection.yaml, dashboards/focus/focus.yaml, dashboards/focus/focus_consolidation_view/focus_consolidation_view.sql, dashboards/health-events/health-events.yaml, dashboards/kpi_dashboard/kpi_dashboard.yaml, dashboards/shard/shard.yaml, terraform/cicd-deployment/README.md
=> massive doc migration

terraform/cicd-deployment/README.md, terraform/cicd-deployment/providers.tf
=> Tf provider

dashboards/aws-budgets/aws-budgets.yaml
=> Remove not used column from the view

cfn-templates/cid-cfn.yml
=> update python runtime to 3.13

dashboards/aws-marketplace/aws-marketplace-spg.yaml
=> SPG update with agreements

changes/CHANGELOG-scad-cca.md, dashboards/scad-containers-cost-allocation/scad-containers-cost-allocation.yaml
=> release scad 3.0

dashboards/scad-containers-cost-allocation/scad-containers-cost-allocation.yaml
=> Removed unnecessary data column from cur2 dependsOn

changes/CHANGELOG-scad-cca.md
=> Update CHANGELOG-scad-cca.md to reflect CPU cost fix

cid/common.py
=> safe parameter detection in lambda

dashboards/tao/tao-definition.yaml, dashboards/tao/tao.yaml
=> tao_v4 fix

dashboards/tao/tao-definition.yaml
=> fix for date conversion and sort order

cid/helpers/parameter_store.py
=> use json prameters

cid/export.py
=> fix-export-of-tables

.github/workflows/codeguru-reviewer.yml, .github/workflows/python-publish.yml, .github/workflows/tests.yml, .github/workflows/tf-test-deployment.yml
=> fix github actions
