aws-solutions-library-samples/cloud-intelligence-dashboards-framework

- cudos/shell-script/lib/common.sh
The customer may have configured their QuickSight deployment in a different region than where they want to deploy the dashboards.  Added an additional "optional" parameter that uses the just selected region as a default, but offers the customer an option to select an alternate region.
This is to avoid the error on "aws quicksight list-users":
An error occurred (AccessDeniedException) when calling the ListUsers operation: Operation is being called from endpoint {dashboard region, e.g. us-west-2}, but your identity region is {identity region, e.g. us-east-1}. Please use the {identity region, e.g. us-east-1} endpoint.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …
> Add parameter for QuickSight identity region

- cudos/shell-script/customer-cudos.sh
Fix "unary operator expected" bug when checking for updates to the cudos dasbboard
*Issue #, if available:* Running dashboard update results in an error "unary operator expected"
*Description of changes:* added quotes around the ${current_dashboard_source_version}, ${latest_template_version} variables in the if statement.
> Fix "unary operator expected" bug

- cid/common.py
Currently if there is a permission error the message is ambiguous. I had to spend 3-4 hours of debugging span other a week :)  AWS side before I realized I could simply alter the code. 
Before vs After where Before is not verbose enough and might be confusing. 
```
Creating dataset: ec2_running_cost...unable to create, missing permissions
Creating dataset: s3_view...unable to create, missing permissions
Creating dataset: summary_view...unable to create, missing permissions
```
After
```
Creating dataset: ec2_running_cost...unable to create, missing permissions, An error occurred (AccessDeniedException) when calling the ListUsers operation: Operation is being called from endpoint us-east-1, but your identity region is eu-central-1. Please use the eu-central-1 …
```
> improve error message, when missing perms

- cfn-templates/cudos-cfn.yml
https://github.com/aws-samples/aws-cudos-framework-deployment/issues/155
Add terminated quotes to query strings for boto3.athena
> fix(athena): Athena query vars missing terminated quotes

- cid/helpers/cur.py
When a huge number of CUR tables detected, it's much more convenient to reverse sort the list allowing more recent tables to appear first in the list
> Enhancement: Sort CUR table names (desc)

- cid/helpers/quicksight.py
*Issue #, if available:* fixes #174
The describe_user call in the user property splits the AWS ARN on `/` and gets the last 2 values from the string. This might cause
issue when the ARN is an IAM User ARN (As described in #174). This commit fixes this behaviour by removing the initial `arn:aws:iam...` string instead.
> fixed describe_user call in user property of QuickSight helper

- cfn-templates/spice-refresh-cfn.yml
*Issue #221 221*
Fix for spice refresh not using the correct prefix if provided. This ensures that when a prefix is defined, it will use the correct value. The `cudos-cfn.yml` always adds `_-` as a default to whatever prefix is added. This will strip that value out and ensure the lambdas created and the env variable being uses match.
> Fix (#221) - Ensure correct prefix is used in spice-refresh.yml

- cid/common.py
- cid/helpers/quicksight/__init__.py
- cid/helpers/quicksight/dashboard.py
As we do autodiscovery of the existing deployments, have resource take-over mechanism and share feature we no longer need to workaround reading legacy `.json` files with deployment info.
> Change: Stop reading legacy deployments information

- cfn-templates/cid-cfn.tests.bats
- cfn-templates/cid-cfn.yml
- cid/cli.py
- cid/common.py
- cid/helpers/quicksight/__init__.py
- cid/logger.py
- cid/test/bats/10-deploy-update-delete/compute-optimizer-dashboard.bats
- cid/test/bats/10-deploy-update-delete/cost_intelligence_dashboard.bats
- cid/test/bats/10-deploy-update-delete/cudos.bats
- cid/test/bats/10-deploy-update-delete/kpi_dashboard.bats
- cid/test/bats/10-deploy-update-delete/ta-organizational-view.bats
- cid/test/bats/10-deploy-update-delete/trends-dashboard.bats
* Autodetect QS identity region in CFN
* Fix issues with Autodetect QS identity region in CID-CMD
* minor changes in automated testing of CID (just speed up)
* Fix issue with datasource listing (as it was breaking automated testing of CFN)
> Autodetect identity region and other fixes

- cid/common.py
This adds a safe fallback for python 3.7.x (where x unknown)
> fix plugin import for python 3.7

- cid/common.py
Raising proper error when Resource ID is missing
> Raising proper error when Resource ID is missing

- cfn-templates/cid-cfn.yml
*Issue #, if available:* None
*Description of changes:* Adds a default value for the "Suffix" CloudFormation parameter. This parameter is documented as for testing purposes only. Defaulting to an empty string allows easier integration for automated deployments, such as via Terraform. Prerequisite for https://github.com/aws-samples/aws-cudos-framework-deployment/pull/480.
> Default cfn template Suffix parameter to empty string

- cfn-templates/cid-cfn.yml
*Issue #, if available:* None
*Description of changes:* Fixes conditional logic for creation of Quicksight data source in CloudFormation. During a previous update, logic was added to not attempt to create a Quicksight datasource in CloudFormation if the region eu-west-3 because that region does not support QS data source creation in CloudFormation. The logic was reversed, however, such that the CF template only attempts to create the datasource in eu-west-3 and does not create it elsewhere. This can cause deployment failures in other regions because it is looking for a datasource `CID-Athena-1` that doesn't exist.
> Fix logic of Quicksight data source creation in CF

- cfn-templates/cid-cfn.yml
*Description of changes:* Adds check to SPICE refresh Lambda function to skip the refresh if there is a recent scheduled refresh (within 25 hours). This prevents potential S3 throttling caused by scheduled and manual (Lambda-invoked) refreshes occurring at the same time.
> Prevent parallel SPICE refresh

- cid/builtin/core/data/queries/cid/summary_view.sql
- cid/builtin/core/data/queries/cid/summary_view_ri.sql
- cid/builtin/core/data/queries/cid/summary_view_sp.sql
- cid/builtin/core/data/queries/cid/summary_view_sp_ri.sql
https://github.com/aws-samples/aws-cudos-framework-deployment/issues/547
Casting the value explicitly so that in case of blank value, view can be created with string data type.
> to fix blank value issue in SP/RI columns

- cid/builtin/core/data/datasets/kpi/kpi_instance_all.json
- cid/builtin/core/data/datasets/kpi/kpi_tracker.json
- cid/builtin/core/data/queries/kpi/kpi_instance_all_view.sql
- cid/builtin/core/data/queries/kpi/kpi_instance_all_view_noRI.sql
- cid/builtin/core/data/queries/kpi/kpi_instance_all_view_noRISP.sql
- cid/builtin/core/data/queries/kpi/kpi_instance_all_view_noSP.sql
- cid/builtin/core/data/queries/kpi/last_kpi_tracker_view.sql
1. kpi_instance_all view updated to include :
MySQL Database Engine in Graviton Savings Calculation
New field showing Oracle and SQL Server database engine cost
2. kpi_tracker view updated to include :
Field flagging RDS resources running on "'License included", "Bring your own license" or "No license required" model
New field showing Oracle and SQL Server database engine cost
> Inclusion of MySQL Database Engine in Graviton Savings Calculation

- dashboards/sustainability-proxy-metrics/sustainability-proxy-metrics.yaml
*Issue #, if available:* us-gov-west-1 is not flagged as a green region, but it should be to reflect the official list available here: https://sustainability.aboutamazon.com/products-services/the-cloud
*Description of changes:* add us-gov-west-1 in the list of green regions
> Add us-gov-west-1 to the list of green regions

- dashboards/sustainability-proxy-metrics/sustainability-proxy-metrics.yaml
Includes all resources costs (not only EC2) on the past month rolling (not 7 months)
> Fix sus_geo_region_athena_view with all costs on last rolling month

- .github/workflows/security-scan.yml
- .pylintrc
> Add pylint and fix CI

- cid/common.py
> remove obsolete code

- cid/helpers/quicksight/__init__.py
do not propose creating one if managed by AD or IAM IC
> better management of groups

- cid/builtin/core/data/queries/co/auto_scale_options.sql
- cid/builtin/core/data/queries/co/ebs_volume_options.sql
- cid/builtin/core/data/queries/co/ec2_instance_options.sql
- cid/builtin/core/data/queries/co/lambda_options.sql
CONCAT function with null values are not working as it returns null if any of columns used in CONCAT function nulls, therefore added coalesce to keep null columns as 'na' and CONCAT function will still work as expected.
COALESCE function added to all option_details columns.
> Fix option_details column

- cid/common.py
- cid/helpers/athena.py
- cid/helpers/quicksight/__init__.py
> Minor fixes

- cid/common.py
- cid/export.py
> Allow SQL datasets export

- cid/helpers/quicksight/__init__.py
In some cases of older boto3 and botocore installed, 
boto3                     1.12.46
botocore                  1.15.46
dashboard.version.get('DataSetArns') can return a None value.
Handle the cases where dashboard.version.get('DataSetArns') returns a None value.
> Bugfix to handle empty datasetarns

- cfn-templates/cid-cfn.yml
> Fixing missing permissions for proper QS functioning after deploy

- .gitignore
- cfn-templates/cid-cfn.yml
Minor edits to names of policies needed for the QS Data Source role to avoid collision.
> Fixed QS Data Source policy name collision

- cfn-templates/cid-cfn.yml
> allways allow access to data collection bucket for account map access

- cid/common.py
- cid/helpers/quicksight/__init__.py
- cid/helpers/quicksight/dashboard.py
- cid/utils.py
> Feature - better status - shows owners and last dataset ingestion  

- cid/builtin/core/data/resources.yaml
- cid/cli.py
- cid/common.py
- cid/export.py
- cid/helpers/quicksight/__init__.py
- dashboards/catalog.yaml
- dashboards/cost-anomalies/cost-anomalies.yaml
- dashboards/data-transfer/DataTransfer-Cost-Analysis-Dashboard.yaml
- dashboards/sustainability-proxy-metrics/sustainability-proxy-metrics.yaml
> Feature catalog

- terraform-modules/README.md
- terraform-modules/cid-dashboards/README.md
- terraform-modules/cid-dashboards/main.tf
- terraform-modules/cur-setup-source/main.tf
- terraform-modules/terraform-test.bats
*Issue #, if available:* #650 #659
Adds template tags to S3 object and fixes issue of continual drift when using KMS default server-side encryption configuration on the S3 `template_bucket`. The etag of objects encrypted with SSE-C or SSE-KMS is not set to the MD5 hash of the object (https://docs.aws.amazon.com/AmazonS3/latest/API/API_Object.html). Terraform instead exposes a `source_hash` used to trigger re-uploads of the S3 objects to work around this issue with the etag.
I've also included tests that plan operations immediately after `terraform apply` do not result in changes when using default settings and when using KMS encryption.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …
> Terraform: S3 object tags and fix for continous drift with KMS-encrypted bucket

- cfn-templates/cid-cfn.yml
- cid/helpers/cur.py
> Add product storage fields and better messages if CUR does not contain fields

- README.md
Hello, I fixed some wrong links on Supported Dashboards. CID Framework was moved to https://catalog.workshops.aws/awscid/en-US
> Fixed supported dashboards links

- cid/common.py
- cid/helpers/account_map.py
- cid/helpers/cur.py
- dashboards/data-transfer/DataTransfer-Cost-Analysis-Dashboard.yaml
> fix account map creation

- dashboards/sustainability-proxy-metrics/sustainability-proxy-metrics.yaml
- removes tax/negation in compute visuals
- extends timeframes of all datasets consistenly to 7 months; removes order by
Update must be done with --force --recursive; DECIMAL SubType FLOAT requires boto3 SDK v1.28.77 or later
> Fixes queries for sustainability proxy metrics dashboard

- dashboards/sustainability-proxy-metrics/sustainability-proxy-metrics.yaml
*Issue #, if available:* This is an update to PR #697.
*Description of changes:* The earlier PR introduced regression, as two restructured views did join the business KPI/ metrics table directly without grouping. This increased the numbers when tags/ accounts had multiple KPI entries per hour. I added the same grouping that the other tables have.
> fixes joins for multiple business metrics per hour

- cfn-templates/cid-cfn.yml
https://github.com/aws-samples/aws-cudos-framework-deployment/issues/705
Adds permissions for glue:GetPartition to the QuickSightDataSourceRole so that the `data_transfer_view` dataset can be added successfully
> fix: add glue:GetPartition action to QuickSightDataSourceRole

- cid/builtin/core/data/resources.yaml
- cid/common.py
- cid/helpers/__init__.py
- cid/helpers/account_map.py
- cid/helpers/cur.py
- cid/helpers/glue.py
> Feature manage cur fields

- cid/builtin/core/data/resources.yaml
1. The QuickSight dataset refresh schedules were not being created for the hourly_view and resource_view datasets.
2. The 'schedules' parameter for these datasets in python/cid/builtin/core/data/resource.yaml was misaligned.
1. Updated the 'schedules' parameter for hourly_view and resource_view in resource.yaml to align properly.
2. This fix should resolve the dataset refresh scheduling issue for hourly_view and resource_view.
> Fix QuickSight dataset refresh schedule creation for hourly_view and resource_view

- cid/export.py
- cid/helpers/quicksight/__init__.py
> Support theme

- .github/workflows/security-scan.yml
- cfn-templates/cid-cfn.yml
- cfn-templates/cur-aggregation.yaml
- cid/common.py
- cid/export.py
> allow CN region and add lint

- cfn-templates/cur-aggregation.yaml
> support cur replication for cn

- .github/workflows/security-scan.yml
- cfn-templates/cid-cfn.yml
> fix managed policy

- dashboards/extended-support-cost-projection/extended-support-cost-projection.yaml
Adding resources for the EKS Extended Support Cost Projection dashboard, including:
- Dashboard definition changes to include a new sheet with the EKS Extended Support Dashboard definition
- Dataset definition
- Data view definition and view creation SQL statement
> Adding EKS Extended Support Cost Projection dashboard definition

- cid/helpers/cur.py
> fix-ri-sp-without-crawler

- terraform-modules/cur-setup-destination/main.tf
- terraform-modules/cur-setup-source/main.tf
Works around apparent bug in checkov https://github.com/bridgecrewio/checkov/issues/6294#
The KMS key rotation is not configured on the aws_s3_bucket_server_side_encryption_configuration resource so it does not make sense to check for it there. Key rotation is outside the scope of this module.
> Exclude CKV2_AWS_67 to workaround checkov bug

- cid/builtin/core/data/queries/cid/summary_view.sql
- cid/builtin/core/data/queries/cid/summary_view_ri.sql
- cid/builtin/core/data/queries/cid/summary_view_sp.sql
- cid/builtin/core/data/queries/cid/summary_view_sp_ri.sql
- cid/builtin/core/data/queries/cudos/hourly_view.sql
- cid/builtin/core/data/queries/cudos/hourly_view_ri.sql
- cid/builtin/core/data/queries/cudos/hourly_view_sp.sql
- cid/builtin/core/data/queries/cudos/hourly_view_sp_ri.sql
- cid/builtin/core/data/queries/cudos/resource_view.sql
- cid/builtin/core/data/queries/cudos/resource_view_ri.sql
- cid/builtin/core/data/queries/cudos/resource_view_sp.sql
- cid/builtin/core/data/queries/cudos/resource_view_sp_ri.sql
Split Allocation Cost Data (SCAD) is not necessary for summary_view, hourly_view, and resource_view as the cost is a subset of other usage. SCAD also uses new fields to visualize cost which is only used in the new SCAD dashboard. 
> Filter scad from views

- cfn-templates/cid-cfn.yml
- cfn-templates/tests/test_deploy_with_permissions.py
> fix crawler permissions

- terraform-modules/README.md
- terraform-modules/cur-setup-destination/README.md
- terraform-modules/cur-setup-source/README.md
The TF Module has unclosed quotes in the HCL snippets.
> fix: close quotes terraform module documentation examples

- terraform-modules/README.md
The link in the base directory for terraform module docs is not
correct.
> fix: update broken link in terraform docs

- dashboards/health-events/health-events.yaml
Resolves issue #855 
Modify query that creates the health_events_view to encapsulate the DB name and view name in quotes. 
> Update SQL statement to encapsulate db name and view in quotes

- terraform-modules/cur-setup-destination/main.tf
- terraform-modules/cur-setup-source/main.tf
As per the AWS Provider documentation at https://registry.terraform.io/providers/hashicorp/aws/5.55.0/docs/data-sources/region#attribute-reference, there is no attribute called `region`. 
Using the module as is results with errors like this:
```
Error: Unsupported attribute
│ 
│   on .terraform/modules/cur_source/terraform-modules/cur-setup-source/main.tf line 127, in data "aws_iam_policy_document" "bucket_policy":
│  127:       values   = ["arn:${data.aws_partition.this.partition}:cur:${data.aws_region.this.region}:${data.aws_caller_identity.this.account_id}:definition/*"]
│ 
│ This object has no argument, nested block, or exported attribute named
│ "region".
```
By submitting this pull request, I confirm that you can use, modify, copy, …
> Fix wrong Terraform attribute for AWS Region

- terraform-modules/cur-setup-destination/main.tf
- terraform-modules/cur-setup-source/main.tf
PR #825 introduced new iam conditions, one of them uses wildcard without Like operator
To be honest I don't even know if the SourceArn is required/valid, but we're currently troubleshooting missing cur reports and making the policy valid is first step.
Right now cur reports issues with S3 bucket permissions
> Attempt fixing S3 resource policy introduced in #825

- terraform-modules/cur-setup-source/main.tf
https://github.com/aws-samples/aws-cudos-framework-deployment/issues/880
> Allow regions other then us-east-1 to create cur via TF

- terraform-modules/cur-setup-destination/main.tf
- terraform-modules/cur-setup-source/main.tf
PR https://github.com/aws-samples/aws-cudos-framework-deployment/pull/825 introduced new iam conditions, one of them uses wildcard without Like operator.
This PR also updates to StringLike for conditions with wildcards for the Get operations ACL as well. This was missing for PR https://github.com/aws-samples/aws-cudos-framework-deployment/pull/879
> Changed to StringLike for conditions with wildcard for Get operations

- changes/CHANGELOG-extended-support-cost-projection.md
- dashboards/extended-support-cost-projection/extended-support-cost-projection.yaml
Adding k8s version 1.30 and dates for start and end of extended support to the EKS view calendar query.
> Update EKS view release and extended support calendar

- README.md
- terraform-modules/README.md
- terraform-modules/cur-setup-destination/README.md
- terraform-modules/cur-setup-source/README.md
*Issue #, if available:* #839, #906
*Description of changes:* Updates to Terraform documentation to eliminate some potential areas of confusion. Also add a more relevant link for the dashboard requirements for those that just need CUR setup to refer to CID workshop rather than the CUR service page.
> TF and general documentation enhancements

- changes/CHANGELOG-extended-support-cost-projection.md
- dashboards/extended-support-cost-projection/extended-support-cost-projection.yaml
Fix: adjusting calculation for extended support price to double the VCPU count for MULTI-AZ databases to cater for the standby database in the multi-az setup. Adjusted titles for price estimation boxes. Adjusted price resolution to ensure provisioned instances take prices from the RDS price table.
> Fixes to extended support price calculations and dashboard price box titles

- changes/CHANGELOG-graviton-opportunities.md
- dashboards/graviton-opportunities-dashboard/graviton_dashboard.yaml
Mordernization mapping updated with missing instance types
* Deleted Target Coverage and Efficiency sliders
* Including Savings Plan covered usage for EC2
* Updated Missing filters for RDS
* Updates to visuals
* New visuals for existing, potential coverage and implementation effort
> Graviton Dashboard 1.1.0

- cfn-templates/cid-admin-policies.yaml
- cfn-templates/cid-cfn.yml
- cfn-templates/data-exports-aggregation.yaml
- cfn-templates/tests/test_deploy_with_permissions.py
- cid/builtin/core/data/resources.yaml
- cid/common.py
- cid/helpers/__init__.py
- cid/helpers/cloudformation.py
- cid/helpers/cur.py
- cid/helpers/iam.py
- cid/helpers/quicksight/datasource.py
> Cur proxy and dataprovider managment

- cid/common.py
- dashboards/catalog.yaml
- dashboards/graviton-savings-dashboard/graviton_legacy.yaml
- dashboards/graviton-savings-dashboard/graviton_savings_dashboard.yaml
> rename to graviton savings dashboard

- terraform-modules/cur-setup-destination/main.tf
- terraform-modules/cur-setup-source/main.tf
*Issue #989, if available:*
Change the region to be us-east-1 for contions in cur bucket policy like the documentation [here](https://docs.aws.amazon.com/cur/latest/userguide/cur-s3.html) because cur definition and billing are just in us-east-1
> fix(tf): cur bucket policy add us-east-1

- cid/base.py
Updates the logic for `domain` property, so that it returns correct domain for GovCloud partition.
> Adds logic to return domain for GovCloud partition

- cid/common.py
- dashboards/cora/cora.yaml
> better error messages and db management

- cfn-templates/cid-cfn.yml
- cfn-templates/cid-plugin.yml
> fix cur table issue

- dashboards/focus/focus.yaml
> added focus consolidation view

- cid/helpers/quicksight/__init__.py
> better messages and names

- cid/common.py
- cid/helpers/quicksight/dashboard.py
- cid/test/bats/10-deploy-update-delete/cudos.bats
> fix update

- cid/helpers/cur_proxy.py
> fix empty fields

- cfn-templates/cid-cfn.yml
> add-crawler-wait

- cid/common.py
cid-cmd deploy fails to get all available dashboards due to failing to get the catalog:
WARNING - Failed to load a catalog url: 403 Client Error: Forbidden for url: https://raw.githubusercontent.com/aws-samples/aws-cudos-framework-deployment/main/dashboards/catalog.yaml
added user agent 
> Adding user agent to get request calls

- cfn-templates/cid-cfn.yml
Add CidDatabase export parameter for CID plugin usage. It will be referenced during CORA dashboard deployment to get account_map table
> Add CidDatabase export parameter for CID plugin usage

- terraform-modules/cur-setup-source/main.tf
*Issue # [1016](https://github.com/aws-samples/aws-cudos-framework-deployment/issues/1016) 
Updates the cur-setup-source module to use aws_iam_role_policy and fix a deprecation warning
> use aws_iam_role_policy to fix deprecation warning

- cid/builtin/core/data/queries/kpi/kpi_ebs_snap_view.sql
Athena view kpi_ebs_snap doesn't give any output due to the bug we fixed here. 
I replaced the splitting sign for billing_period in lines 11 and 12 of kpi_ebs_snap_view SQL query because the original code doesn't output any result from CUR 2.0 data export.
Originally the code tries to split the billing_period var using a forward slash (/) and we replaced it with a dash (-).
> Fix billing_period splitting in kpi_ebs_snap_view sql query

- cfn-templates/cid-cfn.yml
1. Enables deletion of Athena Workgroup via CFN natively, by setting `RecursiveDeleteOption` to true
2. Adds `ExpectedBucketOwner` for better security
> Enables deletion of Athena Workgroup via CFN natively, by setting RecursiveDeleteOption to true

- cid/utils.py
Updates to `get_yesno_parameter` function:
1. Adds type hints to function parameters
2. Attempts to simplify the logic within the function
3. Uses identity comparison ( `is` ) in place of equality ( `==` ) with `None`
4. Converts the `default` value (once it is a `str` type) to lowercase within the function, ensuring case-insensitive comparison regardless of how the `default` is specified.
> Makes parameters of str type case-insensitive

- cid/builtin/core/data/queries/cid/summary_view.sql
- cid/builtin/core/data/queries/cudos/hourly_view.sql
- cid/builtin/core/data/queries/cudos/resource_view.sql
> Fix cur2 consistency

- assets/build_lambda_layer.sh
- assets/publish_lambda_layer.sh
> yaml file copies added into s3 prefix with CID_VERSION

- cid/cli.py
"cid-cmd deploy" accepts --quicksight-group as a parameter however this option is not present in the help. I added --quicksight-group to the help.
> Added quicksight-group to help

- dashboards/extended-support-cost-projection/extended-support-cost-projection.yaml
Adjusting note for EKS upgrade policy reference in the extended support EKS sheet.
> Adjusting note for EKS upgrade policy reference

- changes/CHANGELOG-extended-support-cost-projection.md
- dashboards/extended-support-cost-projection/extended-support-cost-projection.yaml
Fixing existing behaviour for engine, engine version and cluster version controls where selections are being retained across sheets, resulting in mixed values being displayed in controls.
- New individual parameters and controls are now defined for RDS engine and engine version, EKS cluster version, and OpenSearch engine version. Filters on each sheet are associated to their new corresponding parameters.
- Visual titles mentioning 'cost per year' are also adjusted to mention 'monthly cost' instead in alignment with recent changes for the dashboard.
> Fixing existing behaviour for parameters controls mixing values across sheets

- cid/helpers/athena.py
When athena has a large result set we run into the page size of 1,000 items. This PR changes get_query_results to use a paginator and depaginate the result set to support those situations.
> Handle paginated results from athena queries

- cid/builtin/core/data/datasets/kpi/kpi_tracker.json
- cid/builtin/core/data/queries/kpi/last_kpi_tracker_view.sql
- dashboards/kpi_dashboard/kpi_dashboard.yaml
EC2 Previous Generation Coverage and EC2 Spot Coverage must be computed against ec2_usage_cost, not ec2_all_cost.
https://github.com/aws-solutions-library-samples/cloud-intelligence-dashboards-framework/issues/1135
currently the EC2 Previous Generation Coverage and EC2 Spot Coverage are computed against ec2_all_cost while should be computed against the instance usage only
> FIX EC2 Previous Generation Coverage and EC2 Spot Coverage 

- legacy-terraform/README.md
- legacy-terraform/cid-dashboards/README.md
- legacy-terraform/cur-setup-destination/README.md
- legacy-terraform/cur-setup-destination/main.tf
- legacy-terraform/cur-setup-destination/versions.tf
- legacy-terraform/cur-setup-source/README.md
- legacy-terraform/cur-setup-source/main.tf
- legacy-terraform/cur-setup-source/versions.tf
**Title:**
Refactor modules to **legacy-terraform, fix S3 bucket lifecycle rules, update documentation**
**Summary**
Updated all module source paths from terraform-modules/ to legacy-terraform/ in configuration files and documentation for clarity and consistency.
Added the required **filter {} block to all aws_s3_bucket_lifecycle_configuration resources** in cur-setup-destination and cur-setup-source modules to comply with the latest AWS provider validation requirements.
Fixed a reference from **data.aws_region.this.name to data.aws_region.this.id** in cur-setup-source/main.tf for correctness.
Performed minor formatting and documentation improvements across README files.
**Motivation & Context**
These changes:
Address AWS provider warnings about missing filter attributes in S3 lifecycle …
> Refactor modules to legacy-terraform, fix S3 bucket lifecycle rules, update documentation

- legacy-terraform/README.md
- legacy-terraform/cur-setup-destination/main.tf
Changed references from terraform-module to legacy-terraform.
Updated S3 region reference: replaced aws_region.name with aws_region.id.
> update documentation and S3 region reference to use aws_region.id

- cid/builtin/core/data/resources.yaml
Customers complain that cannot do cur query with cur2 in cud_cur database and they need to switch to cid_data_exports every time. This PR will add cur2_view that can be used as access.  
1. cur2 name can be taken in cid_data_exports
2. * can be problematic when working with cur2_proxy
3. cur2_proxy also can be an option but then it would not be trivial to undersand if cur2 or cur1 was used
4. theoretically we can point all cur views to this view adding a common placeholder for all cur related queries that can be modified centrally.  
This pull request introduces the `cur2_view` SQL view and updates dependencies for the `summary_view` in `resources.yaml`.
- **Added `cur2_view`:**
- New view `cur2_view` is defined in `resources.yaml`.
- The …
> add cur2_view

- cid/helpers/cur.py
*Issue* #1283 
Split the parameter over the . (DOT)
```
database, table = answer.split(".")
```
Then, I was able to run the following command line without issue
```
cid-cmd update --force --recursive --dashboard-id kpi_dashboard --on-drif override --yes \
--athena-database "cid_cur" --athena-workgroup CID --cur-table-name-and-db "cid_cur.cur" \
--resource-tags '' --timezone 'Europe/Rome' --taxonomy '[]'
```
> Fix issue #1283 - Command line parsing issue for database and table in cur

- dashboards/focus/focus_consolidation_view/focus_consolidation_view.sql
This PR fixes the issue where Google Cloud `ServiceCategory` in the FOCUS dataset was being handled as a concatenated array.  
Instead of joining the array elements, this change ensures that the **second element of the array** is used as the `ServiceCategory`.  
In Google Cloud FOCUS exports, the `ServiceCategory` field is delivered as an array.  
For example:  [GCP, Network, Cloud Armor, Cloud Armor Standard, Paygo, Rule]
The second element (`Network` in this example) represents the actual `ServiceCategory` that should be aligned with AWS and other providers.
Fixes #1291
> Fix: align Google Cloud ServiceCategory with AWS format (Fixes #1291)
